[package]
name = "private"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fernet = "0.2.0"
rpassword = "7.2.0"
base64 = "0.20.0"